### ISSUE TITLE
[cappuccino milestone] VID optimization

### ISSUE THREAD

**Issue by ggutoski** [EspressoSystems/jellyfish-compat#29]
# Parallel workstreams

- [x] EspressoSystems/jellyfish#393 
  - [ ] A solution for ☝️ might also solve EspressoSystems/jellyfish-compat#31 
  - [ ] Potential blocker: EspressoSystems/jellyfish#463 
- [x] EspressoSystems/jellyfish#469 
- [x] EspressoSystems/jellyfish#470 
- [ ] EspressoSystems/jellyfish-compat#24 
- [x] EspressoSystems/jellyfish-compat#22 
- [ ] EspressoSystems/jellyfish-compat#32 

# Misc low-level discrete tasks
- [x] EspressoSystems/jellyfish#479 
- [x] EspressoSystems/jellyfish#417
